version: '3'

networks:
    network-eureka:
services:
    eureka-server:
        container_name:
            jpetstore-eureka-container
        image: springcloud/eureka
        ports:
            - "8761:8761"
        networks:
            - network-eureka
    frontend:
        container_name:
            Frontend
        build: './Frontend'
        ports:
            - "8080:8080"
        environment:
            - SERVER_HTTP=http://eureka-server:8761/eureka/
        depends_on:
            - eureka-server
        networks:
            - network-eureka
    accountms:
        container_name:
            AccountMS
        build: './AccountMS'
        ports:
            - "8082:8082"
        environment:
            - SERVER_HTTP=http://eureka-server:8761/eureka/
        depends_on:
            - eureka-server
        networks:
            - network-eureka
    orderms:
        container_name:
            OrderMS
        build: './OrderMS'
        ports:
            - "8083:8083"
        environment:
            - SERVER_HTTP=http://eureka-server:8761/eureka/
        depends_on:
            - eureka-server
        networks:
            - network-eureka
    catalogms:
        container_name:
            CatalogMS
        build: './CatalogMS'
        ports:
            - "8084:8084"
        environment:
            - SERVER_HTTP=http://eureka-server:8761/eureka/
        depends_on:
            - eureka-server
        networks:
            - network-eureka
